test(flagd): rework e2e tests to new format
open-feature/java-sdk-contrib pull request #1115
Opened 2024-12-28 16:27 UTC by aepfli

2025-01-15 11:36 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/common/GrpcConnectorTest.java
> +    @Disabled("not sure this test makes sense in this kind of way")
if it is okay, i will delete it

2025-01-15 12:34 UTC, aepfli commented
blocked by https://github.com/open-feature/flagd-testbed/pull/184

2025-01-15 12:57 UTC, warber commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/common/ChannelMonitor.java
> +            // log.info("Channel state changed to: {}", currentState);
should we change this to debug?

2025-01-15 12:58 UTC, warber commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +    private final ScheduledExecutorService reconnectExecutor;
I think we should rename this to e.g. `scheduledErrorNotifier` or something and adjust the doc.

2025-01-15 13:32 UTC, warber commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/common/GrpcConnectorTest.java
> +    @Disabled("not sure this test makes sense in this kind of way")
i also think this does not make sense anymore

2025-01-15 16:15 UTC, toddbaert commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/State.java
> +public class State {
Oh this is an interesting approach, I like it.

2025-01-15 16:21 UTC, toddbaert commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +                    break;
Maybe for consistency we should also extract this into a method but it's a nit.

2025-01-15 16:53 UTC, toddbaert commented
Every run I get a timeout locally on 1 assertion:

```
@rpc @in-process @grace
Scenario: Provider events chain ready -> stale -> error -> ready # test-harness/gherkin/events.feature:21
  Given a stable flagd provider                                  # dev.openfeature.contrib.providers.flagd.e2e.steps.ProviderSteps.setupProvider(java.lang.String)
  Given a ready event handler                                    # dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps.a_stale_event_handler(java.lang.String)
  And a error event handler                                      # dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps.a_stale_event_handler(java.lang.String)
  And a stale event handler                                      # dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps.a_stale_event_handler(java.lang.String)
  Then the ready event handler should have been executed         # dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps.eventHandlerShouldBeExecuted(java.lang.String)
  When the connection is lost for 6s                             # dev.openfeature.contrib.providers.flagd.e2e.steps.ProviderSteps.the_connection_is_lost_for(int)
  Then the stale event handler should have been executed         # dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps.eventHandlerShouldBeExecuted(java.lang.String)
  
  // HANGS HERE FOR A WHILE AND THEN:
  
  Then the error event handler should have been executed         # dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps.eventHandlerShouldBeExecuted(java.lang.String)
      org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in dev.openfeature.contrib.providers.flagd.e2e.steps.EventSteps was not fulfilled within 30 seconds.
```

2025-01-15 17:09 UTC, toddbaert commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/ProviderSteps.java
> +        proxy.toxics().timeout(timoutName, ToxicDirection.DOWNSTREAM, seconds);
I had to change this to downstream to fix my issue... hopefully it doesn't break the e2e tests in CI, but TBH this setting makes more sense to me. :thinking:

2025-01-15 17:22 UTC, toddbaert commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/ProviderSteps.java
> +        proxy.toxics().timeout(timeoutUpName, ToxicDirection.UPSTREAM, seconds);
OK I had to change it to BOTH directions.

2025-01-15 17:27 UTC, toddbaert approved these changes
Amazing work. Minor nit and I made one small change [here](https://github.com/open-feature/java-sdk-contrib/pull/1115#discussion_r1917066303) which I hope you don't mind. Otherwise on my system the timeout was not detected.

2025-01-15 20:09 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/resolver/common/GrpcConnectorTest.java
> +    @Disabled("not sure this test makes sense in this kind of way")
deleted

2025-01-15 21:05 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +                    break;
Extracted

2025-01-15 22:45 UTC, aepfli commented
All dependencies are resolved. Ready to merge ;)

2025-01-16 10:29 UTC, warber commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/storage/connector/grpc/GrpcStreamConnector.java
> +                log.info("stream");
```suggestion
```

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +        Util.busyWaitAndCheck(this.deadline + 500, () -> initialized);
Do we really want to wait busily?

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +        if (reconnectTask != null && !reconnectTask.isCancelled()) {
Don't we also have to cancel the `errorExecutor`?

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +                        log.debug(
I think we should also check here in a thread safe manner if we are still in a stale/error state

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +    private void onProviderEvent(FlagdProviderEvent flagdProviderEvent) {
Is there a mechanism somewhere to ensure that this method is only ever executed by a single thread at a time?

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/EventSteps.java
> +    private static @NotNull ProviderEvent mapEventType(String eventType) {
Could this be a candidate for the Utils class?

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunRpcTest.java
> +// @SelectFile("test-harness/gherkin/rpc-caching.feature")
remove?

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunInProcessTest.java
> +// @SelectFile("test-harness/gherkin/connection.feature")
remove?

2025-01-16 13:55 UTC, chrfwow commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
>              this.flagResolver.shutdown();
```java
this.flagResolver.shutdown();
this.reconnectTask.cancel(true);
```
do we need to cancel the `reconnectTask` as well?

2025-01-16 14:15 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +    private void onProviderEvent(FlagdProviderEvent flagdProviderEvent) {
I have to admit I am not good with concurrency. But I am not sure we must ensure this is only executed once. (naive thought). The `previousEvent` is volatile, so we should see modification throughout all threads (naive knowledge). Or is my understanding wrong here, or do i miss some crucial possibilities?

2025-01-16 14:18 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +        if (reconnectTask != null && !reconnectTask.isCancelled()) {
Please provide a little bit more reasoning. I am unsure what you're aiming at; why should I cancel the errorExecutor, too? The executor is used for the whole instance and is only canceled when shut down. So I can feed new tasks into it on demand. Ultimately, I want to ensure that the reconnect task is not executed. But I still want to continue using my executor.

2025-01-16 16:42 UTC, toddbaert commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +    private void onProviderEvent(FlagdProviderEvent flagdProviderEvent) {
I think @chrfwow is right about this one, we don't want any method calls here to interleave or we can end up in weird states.

2025-01-16 17:28 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/steps/EventSteps.java
> +    private static @NotNull ProviderEvent mapEventType(String eventType) {
It is specific to the events, hence I do not think it is worth to migrate to a different file.

2025-01-16 17:29 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunRpcTest.java
> +// @SelectFile("test-harness/gherkin/rpc-caching.feature")
I left this on purpose, so if somebody wants to test a dedicated feature file, they do have a pointer ok how to do it.

2025-01-16 17:29 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunRpcTest.java
> +// @SelectFile("test-harness/gherkin/rpc-caching.feature")
But adding a comment might be a good idea

2025-01-16 17:30 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
>              this.flagResolver.shutdown();
I will rename the task, but it is executed via the error executor - so it will be cancelled in the next line anyways

2025-01-16 17:41 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +        Util.busyWaitAndCheck(this.deadline + 500, () -> initialized);
For now, yes, this has just been moved further down to up here.

We should generate a task to tackle this specifically on its own and maybe use a more elegant solution. Suggestions and issues are highly welcome.

2025-01-16 17:41 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +    private void onProviderEvent(FlagdProviderEvent flagdProviderEvent) {
added synchronized to the method

2025-01-16 17:41 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunRpcTest.java
> +// @SelectFile("test-harness/gherkin/rpc-caching.feature")
added comment

2025-01-16 17:42 UTC, aepfli commented on providers/flagd/src/test/java/dev/openfeature/contrib/providers/flagd/e2e/RunInProcessTest.java
> +// @SelectFile("test-harness/gherkin/connection.feature")
added comment to signal the purpose of this commented out code

2025-01-16 18:36 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +                        log.debug(
added thank you nice catch

2025-01-16 18:37 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +        Util.busyWaitAndCheck(this.deadline + 500, () -> initialized);
created https://github.com/open-feature/java-sdk-contrib/issues/1160 to tackle this in a nicer way

2025-01-17 07:08 UTC, chrfwow requested changes

2025-01-17 07:08 UTC, chrfwow commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +            enrichedContext = contextEnricher.apply(flagdProviderEvent.getSyncMetadata());
Writing to `syncMetadata` and `enrichedContext` should also happen in the synchronized block to be consistent with `previousEvent`. I think locking on the `eventLock` is fine (as opposed to locking on `this`, which I believe could make problems with the `initialize` method, but I am not 100% sure)

2025-01-17 12:34 UTC, aepfli commented on providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/FlagdProvider.java
> +            enrichedContext = contextEnricher.apply(flagdProviderEvent.getSyncMetadata());
Done in the latest push

2025-01-20 07:31 UTC, chrfwow approved these changes

2025-01-20 19:56 UTC, toddbaert commented
I pushed [one more small change](https://github.com/open-feature/java-sdk-contrib/pull/1115/commits/3d2b826deb70f5e7d8a232e61657340545b5fa61) to move all the volatile fields on the provider into a dedicated object to be used as the intrinsic lock in our synchronized blocks. I think this has the benefit of being very clear but also it unifies all our locking onto a single object.

2025-01-20 19:56 UTC, merged